+ ENV=Walker2d-v2
+ NUM_ENV=1
+ SEED=200
+ BUF_LOAD=/root/project/dataset/sac/Walker2d-v2
+ VF_HIDDEN_SIZES=100
+ D_HIDDEN_SIZES=100
+ POLICY_HIDDEN_SIZES=100
+ NEURAL_DISTANCE=True
+ GRADIENT_PENALTY_COEF=10.0
+ L2_REGULARIZATION_COEF=0.0
+ REWARD_TYPE=nn
+ TRPO_ENT_COEF=0.0
+ LEARNING_ABSORBING=False
+ TRAJ_LIMIT=3
+ TRAJ_SIZE=1000
+ ROLLOUT_SAMPLES=1000
+ TOTAL_TIMESTEPS=3000000
++ uname
+ '[' Linux == Darwin ']'
++ uname
+ '[' Linux == Linux ']'
+ for ENV in "Walker2d-v2" "HalfCheetah-v2" "Hopper-v2"
+ BUF_LOAD=/root/project/dataset/sac/Walker2d-v2
+ for SEED in 100 200 300
+ python3 -m gail.main -s
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2022-04-30 22:56:16,799161 - lunzi/nn/patch.py:31 - Monkey patching TensorFlow...
2022-04-30 22:56:41,981214 - lunzi/config.py:90 - no config file specified.
2022-04-30 22:56:48.343423: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2022-04-30 22:56:48.346094: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2299995000 Hz
2022-04-30 22:56:48.346317: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x2bc89a0 executing computations on platform Host. Devices:
2022-04-30 22:56:48.346358: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2022-04-30 22:56:48,346822 - utils/flags.py:209 - Setting random seed to 100
fatal: unable to stat 'utils/__pycache__/timeit.cpython-37.pyc': No such file or directory
Command '['git', 'add', '.']' returned non-zero exit status 128.
Try again...
[Errno 2] No such file or directory: 'logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/diff.patch'
Try again...
error: unable to read sha1 file of logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/=1.3 (a4fd445cd9e14c7987c52e803bef9215d1910ab1)
error: unable to read sha1 file of logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac.tar.xz (9a49440d0162d27f2e5326654de939ace8300989)
error: unable to create file logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/Ant-v2/expert_replay_buffer.index: No such file or directory
error: unable to create file logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/Ant-v2/expert_replay_buffer.meta: No such file or directory
error: unable to create file logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/Ant-v2/policy.npy: No such file or directory
error: unable to create file logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/HalfCheetah-v2.h5: No such file or directory
fatal: cannot create directory at 'logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/HalfCheetah-v2': No such file or directory
Command '['git', 'checkout-index', '-a', '-f', '--prefix=logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/']' returned non-zero exit status 128.
Try again...
error: unable to read sha1 file of logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/=1.3 (a4fd445cd9e14c7987c52e803bef9215d1910ab1)
error: unable to read sha1 file of logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac.tar.xz (9a49440d0162d27f2e5326654de939ace8300989)
error: unable to create file logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/Hopper-v2.h5: No such file or directory
fatal: cannot create directory at 'logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/Hopper-v2': No such file or directory
Command '['git', 'checkout-index', '-a', '-f', '--prefix=logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/']' returned non-zero exit status 128.
Try again...
fatal: Unable to write new index file
Command '['git', 'add', '.']' returned non-zero exit status 128.
Try again...
error: unable to read sha1 file of logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/=1.3 (a4fd445cd9e14c7987c52e803bef9215d1910ab1)
error: unable to read sha1 file of logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac.tar.xz (9a49440d0162d27f2e5326654de939ace8300989)
error: unable to create file logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/Reacher-v2.h5: No such file or directory
fatal: cannot create directory at 'logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/Reacher-v2': No such file or directory
Command '['git', 'checkout-index', '-a', '-f', '--prefix=logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/']' returned non-zero exit status 128.
Try again...
fatal: Unable to write new index file
Command '['git', 'add', '.']' returned non-zero exit status 128.
Try again...
error: unable to read sha1 file of logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/=1.3 (a4fd445cd9e14c7987c52e803bef9215d1910ab1)
error: unable to read sha1 file of logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac.tar.xz (9a49440d0162d27f2e5326654de939ace8300989)
error: unable to create file logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/Reacher-v2/policy.npy: No such file or directory
error: unable to create file logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/Swimmer-v2.h5: No such file or directory
fatal: cannot create directory at 'logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/Swimmer-v2': No such file or directory
Command '['git', 'checkout-index', '-a', '-f', '--prefix=logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/']' returned non-zero exit status 128.
Try again...
fatal: Unable to write new index file
Command '['git', 'add', '.']' returned non-zero exit status 128.
Try again...
error: unable to read sha1 file of logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/=1.3 (a4fd445cd9e14c7987c52e803bef9215d1910ab1)
error: unable to read sha1 file of logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac.tar.xz (9a49440d0162d27f2e5326654de939ace8300989)
error: unable to create file logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/Swimmer-v2/policy.npy: No such file or directory
error: unable to create file logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/Walker2d-v2.h5: No such file or directory
fatal: cannot create directory at 'logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/dataset/sac/Walker2d-v2': No such file or directory
Command '['git', 'checkout-index', '-a', '-f', '--prefix=logs/baseline-Hopper-v2-100-2022-04-30-22-56-48/src/']' returned non-zero exit status 128.
Try again...
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/.shortcut-targets-by-id/1lw-oqXVYCBflGoGWsmuu-2ACDAbJa2IS/GAIL-Lab/project/gail/main.py", line 216, in <module>
    main()
  File "/content/drive/.shortcut-targets-by-id/1lw-oqXVYCBflGoGWsmuu-2ACDAbJa2IS/GAIL-Lab/project/gail/main.py", line 61, in main
    FLAGS.freeze()
  File "/content/drive/.shortcut-targets-by-id/1lw-oqXVYCBflGoGWsmuu-2ACDAbJa2IS/GAIL-Lab/project/lunzi/config.py", line 63, in freeze
    self.finalize()
  File "/content/drive/.shortcut-targets-by-id/1lw-oqXVYCBflGoGWsmuu-2ACDAbJa2IS/GAIL-Lab/project/utils/flags.py", line 251, in finalize
    raise RuntimeError('Failed after 10 trials.')
RuntimeError: Failed after 10 trials.
